### PR TITLE
Correct router helper register

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
The goal of this is to make a PR for main joomla cms.

The component router helper should be registered in the component association helper.

Please test.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
BTW this also needs to be corrected in weblinks repository

**Comment by infograf768** [comment]
test instructions?

**Comment by andrepereiradasilva** [comment]
associations tabs work fine in all componens that supports associations.

**Comment by andrepereiradasilva** [comment]
folks please test and code review so we get this into joomla cms staging and weblinks staging

**Comment by jreys** [comment]
No problems found here

**Comment by alikon** [comment]
Not sure wich is better  JPATH_ROOT or JPATH_SITE  or JPATH_BASE ect

https://github.com/joomla/joomla-cms/blob/a0f1f5a7b27d8a1ae2c60c4d244abb3be7eea1c7/administrator/components/com_content/views/articles/tmpl/modal.php#L19

jokes apart seems ok to  me

**Comment by alikon** [comment]
can i merge ?

**Comment by infograf768** [comment]
it should be proposed asap to main staging imho, and then we try to get it in 3.6.1

**Comment by jreys** [comment]
agree

**Comment by alikon** [comment]
but i guess it is needed for successfully test #17

**Comment by andrepereiradasilva** [comment]
yes nicola

i will proposed this to joomla-cms and weblinsk repository

**Comment by alikon** [comment]
not so sure if this move is correct for later re-merging with joomla-cms staging ....

**Comment by alikon** [comment]
i'm a git dumb

**Pull request merged**
