### PR TITLE
Solving tmpl=component issue

### PR DESCRIPTION
**Pull request by jreys**
Pull Request for [this comment](https://github.com/joomla-projects/gsoc16_improved-multi-lingual/issues/70#issuecomment-238791019)

### CODE REVIEW

**Comment by jreys** [comment]
This might not be the best approach since the load is being done twice, can't find another way though

**Comment by infograf768** [comment]
will test tomorrow

**Comment by infograf768** [comment]
@jreys This does not work

**Comment by infograf768** [comment]
If I comment this way

``` js
        //if (this.src.indexOf('&tmpl=component') === -1)
        //{
            this.src += '&tmpl=component';
        //}
```

Then it works after loading twice indeed. BUt it gets into a loop.

**Comment by andrepereiradasilva** [comment]
IMHO, shouldn't be solved by com_associations
3º party component need to correctly support tpml=component to work in com_associations

we should drop this PR and made that clear in the documentation

**Comment by alikon** [comment]
> we should drop this PR and made that clear in the documentation

should be a good solution

**Comment by infograf768** [comment]
Closed then...

**Pull request closed without merging**
