### PR TITLE
Fixing associations not showing for categories in list view

### PR DESCRIPTION
**Pull request by jreys**
#### Summary of Changes

Associations where not showing for categories in list view

### CODE REVIEW

**Comment by infograf768** [comment]
Can you clean up this PR? It contains stuff which has no relation with the Categories associations not showing in list view.

**Comment by infograf768** [comment]
Anyway, https://github.com/joomla-projects/gsoc16_improved-multi-lingual/pull/20 solves that one. I guess we can close it and concentrate on #20

**Comment by andrepereiradasilva** [comment]
i think after merging https://github.com/joomla-projects/gsoc16_improved-multi-lingual/pull/20 your life will be easier.

in 20 i created a helper function that returns a JRegistry object with all the component/extension properties.

`AssociationsHelper::getComponentProperties($component);`

Examples:

``` php
$object = AssociationsHelper::getComponentProperties('com_content.article');
$object = AssociationsHelper::getComponentProperties('com_categories.category|com_content');
$object = AssociationsHelper::getComponentProperties('com_menus.item');
```

Will get for that component/item/extension:

``` php
$object->component           // Component identifier (ex: com_content)
$object->item                // Component item identifier (ex: article)
$object->extension           // Component extension identifier , for categories (ex: null)
$object->associationsContext // The component item associations context (ex: com_content.item)
$object->typeAlias           // The component item type alias (ex: com_content.article)
$object->table               // The component item db table (ex: #__content)
$object->tableFields         // An array of db table fields
$object->fields              // The fields for dynamic list view
$object->excludeOrdering     // Array of field to exclude in list ordering
$object->associationKey      // Association layout key ??????????
$object->assetKey            // The component item asset key for ACL
```

**Comment by jreys** [comment]
Fixed by #20 no need for it anymore.

**Pull request closed without merging**
