### PR TITLE
[PostgreSql] - wrong group by  in list view

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue  wrong SQL group by  in  list view .
#### Summary of Changes

``` php
->group($db->quoteName(array('a.id', 'title', 'language')));
```

changed accordigly with selected fields
#### Testing Instructions

please test on mysql too 
need to be tested on MSSQL

code review

### CODE REVIEW

**Comment by alikon** [comment]
please don't test still work in progress

**Comment by alikon** [comment]
need to be tested on 3dp as well

**Comment by infograf768** [comment]
@test
did not remark any issue with mysqli list view, including third party component

**Comment by andrepereiradasilva** [comment]
tested ok on code review!

**Comment by andrepereiradasilva** [comment]
merging

**Pull request merged**
