### PR TITLE
Fix menu parent id in component view

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

Access `/administrator/index.php?option=com_menus&view=item&menutype=&layout=edit&tmpl=component`

Before patch Menu parent field shows admin menu items

image

After patch does not show.

### CODE REVIEW

**Comment by jreys** [comment]
Tested, doesn't break anything I can think off :)

**Comment by infograf768** [comment]
In fact we DO need this in core as we DO have a bug when creating a new menu item in menu items manager.

When a menu has not been set, i.e. when we display the menu item manager with all menu items, and want to create a new menu item. If one clicks on the parent Item dropdown first, it displays all menu items including back-end until a specific menu is chosen.

I suggest to make a PR to core.

**Comment by infograf768** [comment]
@andrepereiradasilva

**Comment by andrepereiradasilva** [comment]
PR done in main CMS

**Pull request closed without merging**
