### PR TITLE
Moving side by side css to the media folder

### PR DESCRIPTION
**Pull request by infograf768**
To test, check source 
simple way to test RTL: change en-GB.xml:
`<rtl>1</rtl>`

### CODE REVIEW

**Comment by alikon** [comment]
work for me

**Comment by andrepereiradasilva** [comment]
sorry guys but i don't understand why having a specifi rtl css ... when you do all ok that with just css.

you can just prepend the rtl classes overrides with 

``` css
html[dir=rtl]
```

example:

``` css
/* LTR (default) */
.sidebyside .outer-panel {
    float: left;
    width: 50%;
}

/* RTL (override) */
html[dir=rtl] .sidebyside .outer-panel {
    float: right;
}
```

**Comment by infograf768** [comment]
@andrepereiradasilva 
Having a specific rtl css is what we always did and it makes things easier to read / and understand.
- I never heard about this kind of markup...
  `html[dir=rtl]`

**Comment by andrepereiradasilva** [comment]
See https://github.com/joomla/joomla-cms/search?q=html%5Bdir%3Drtl%5D

**Comment by infograf768** [comment]
Can we keep the old way please? ❕

**Comment by andrepereiradasilva** [comment]
of course we can.

But is not IMHO the most correct way of doing thing.
for instance, this means if you changes the `.sidebyside #right-panel .inner-panel` class to have a border of 2px, you have to change in two files. 

This way we just change in one file ... so is more efficient.
For me is clearly is a better option. but if you insist in doing this way go ahead.

**Comment by infograf768** [comment]
http://rishida.net/blog/?p=671#comment-10058

**Comment by infograf768** [comment]
I really prefer the good old way. No chance to mistake.

**Comment by andrepereiradasilva** [comment]
My opinion is that `old way` is clearly less eficient and harder to mantain and more mistake prone (ex: forget to change one the files when making a change ...).

But ... i will not discuss this anymore. If you want to merge it like this. Go ahead.

**Pull request closed without merging**
