### PR TITLE
fix ACL on update

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #93.
### Summary of Changes

cloned rules from com_content when update
### Testing Instructions

check that ACL  when update have the same rules as for com_content for core.admin, core.manage

see #101

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
cs

**Comment by andrepereiradasilva** [comment]
@alikon i'm still not enterrily convinced we should copy the com_content permissions, can't we create a access security issue with this?

isn't it better (or at least more safe) to check the user groups "Manager" and "Administrator" have the same ids as the install and if so use them, if not don't do anything?

**Comment by alikon** [comment]
the most easy thing that we can do is do like other new core components behave on update (nothing) ....

**Comment by andrepereiradasilva** [comment]
do you think we should ask the PLT an opinion for this? maybe there is another way?

**Comment by alikon** [comment]
Why not we are open to listen more experienced people ;)

**Comment by infograf768** [comment]
maybe contact the weblinks people as i discovered they indeed do nothing atm and my manager could not access to weblinks. Had to manually set it by a superuser.

**Comment by andrepereiradasilva** [comment]
lol

**Comment by alikon** [comment]
the com_weblinks as it is decoupled not more a core components, is not a correct example i think

**Comment by andrepereiradasilva** [comment]
see michael comment https://github.com/joomla/joomla-cms/pull/11834/files/9ac28b8c2c14b7b6b79e963a5ea20fc0041b7dc2#r76787099

**Comment by alikon** [comment]
if i've understand well micheal comment we already do this , we still need to decide if we want to clone rules from com_content or not

**Comment by andrepereiradasilva** [comment]
IMHO we close this and do what all the other components do

**Comment by alikon** [comment]
yes fine for me

**Comment by andrepereiradasilva** [comment]
closing

**Pull request closed without merging**
