### PR TITLE
Adding compressed and uncompressed js files

### PR DESCRIPTION
**Pull request by jreys**
Pull Request for Issue #94 .
### Summary of Changes

Added the compressed JS file.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
@jreys today or tomorrow i will update staging (need to fix conflicts with more azure files) them will test this also.

If ok, will merge it.

**Comment by alikon** [comment]
:thumbsup:

**Comment by andrepereiradasilva** [comment]
All seems ok

**Comment by andrepereiradasilva** [comment]
merged

**Pull request merged**
