### PR TITLE
Adding copy button action

### PR DESCRIPTION
**Pull request by jreys**
Pull Request for Issue #8 and #94.
#### Summary of Changes

Copy all now working, test to see if this is a good way, IMO it's slow but it's the only way to do save & copy and getting the new ID.

Copy field by field not yet implemented
#### Testing Instructions

Check if copy all is working properly, it will only show up when there's a language selected

### CODE REVIEW

**Comment by infograf768** [comment]
Tested with articles. Looks like working here.
will test others later.

**Comment by infograf768** [comment]
Tested categories. I see only one small issue: when changing title of target after copy and then save target, the association is not updated in the reference (but it is in manager). It is only updated in reference when saving reference.

Screeenshots: Reference is 

> subsubcat it-IT



Going side by side
 

Copy reference


Reference displays new association


**Changing Target title and saving: reference is not updated**

5_aftersavemanager

Manager shows new name fine and items are already associated
6-manager

reference is updated after save
aftersavereference

NOTE: after saving reference the scroll bars disappear. I got them first by modifying edit.php
See: https://github.com/joomla-projects/gsoc16_improved-multi-lingual/issues/100#issuecomment-240317284

**Comment by infograf768** [comment]
Copying reference menu items gives:
[17-Aug-2016 07:15:41 UTC] PHP Notice:  Undefined index: associations in ROOT/administrator/components/com_menus/models/item.php on line 1384

Copying reference category gives
[17-Aug-2016 07:17:33 UTC] PHP Notice:  Undefined index: associations in ROOT/administrator/components/com_categories/models/category.php on line 575

**Comment by infograf768** [comment]
NOTE: A 3rd party component needs in its model a CORRECT  `generateNewTitle()` method for `Save as Copy` in order to copy reference, otherwise we get the error (here for Sermonspeaker:
`COM_SERMONSPEAKER_ERROR_ALIAS="This alias is already used for another item (remember it may be a trashed item)."`

**Comment by infograf768** [comment]
We may have to enable in com_associations a custom generatenewtitle in case the 3rd party component does not implement Save as Copy (save2copy) correctly.

**Comment by infograf768** [comment]
https://github.com/joomla-projects/gsoc16_improved-multi-lingual/pull/104#issuecomment-240333325
has PRs in core. One merged, the other waiting https://github.com/joomla/joomla-cms/pull/11664

EDIT: both now merged

**Comment by infograf768** [comment]
@jreys 

Please try to solve **now** the issue I explained above: changing target title (and saving Target) does not change on the fly the association in the Reference item in the same view.

**Comment by infograf768** [comment]
@jreys
Concerning the copying of items when there is no generatenewtitle for Save as Copy

I found out that if we change the alias of the reference, then the copy is done OK after some refreshing of the reference item. Otherwise we get the error BUT with the full admin menus in the Iframe

Can you propose a solution?

**Comment by infograf768** [comment]
@jreys
When I use sermon speaker and save Reference or Target (not category), the admin menus show.
Any idea how to solve this or add something to the requirements?

screen shot 2016-08-25 at 08 44 52

The reason is they do not have the Edit part in their modal. Can we trace this to prevent these items from being taken care of in com_associations if we can't solve ourseleves?

Maybe check if Apply contains `&amp;tmpl=component` and add it if not?

**Comment by andrepereiradasilva** [comment]
we already talked befora about this JM.
it needs to be a requirement.

**Comment by infograf768** [comment]
The problem, Andre, is that we do not check (or can't check) and the way com_associations works, it will propose the concerned items to com_associations, even if not fully compatible.

**Comment by infograf768** [comment]
Anyhow this surely can be solved
https://github.com/joomla-projects/gsoc16_improved-multi-lingual/pull/104#issuecomment-242291882

**Comment by andrepereiradasilva** [comment]
JM, that i know of, we have no way of checking this in the model or table.
So it must be a requirement

**Comment by infograf768** [comment]
tks, @jreys 
This has solved the issue of modifying the target name.

@andrepereiradasilva 
We can merge this if compatible with PLT requirements, i.e. if it has no effect on a change to the way we fetch the necessary informations for Items and table in a new helper.

**Comment by andrepereiradasilva** [comment]
merged

**Pull request merged**
